config/routes.rb
Rails.application.routes.draw do


  get '/auth/google_oauth2', as: :sign_in_with_google
  get '/auth/facebook', as: :sign_in_with_facebook

  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook/callback' => 'callbacks#facebook'


  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'
  # get '/posts/new' => 'posts#new', as: :posts
  # post 'posts/new' => 'posts#create'
  #
  # get 'posts/:id' => 'posts#show', as: :post
  #
  # get 'posts/' => 'posts#index', as: :all_posts
  #
  # get 'posts/:id/edit' => 'posts#edit', as: :edit_post
  #
  # patch 'posts/:id' => 'posts#update'
  # delete 'posts/:id' => 'posts#destroy'
  #
  # get 'next_page' => 'posts#next', as: :next_page

  resources :posts do
    resources :comments
    resources :favourites, only: [:create, :destroy]
  end

  resources :users  do

    get :edit, on: :collection
    patch :update, on: :collection
    delete :destroy, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection #this bypasses having id in the url
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true, uniqueness: {scope: :post_id}

  def comment_snippet
    if self.body.length > 140
      return "#{self.body[0..139]}..."
    else
      return self.body
    end
  end

  def user_full_name
    if user
      user.full_name
    else
      'Anonymous'
    end
  end

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user
  # before_action :authorize_user,  only: [:destroy, :edit, :update]

  def create

    @post = Post.find params[:post_id]
    comment_params = params.require(:comment).permit(:body, :post_id)
    @comment = Comment.new comment_params
    @comment.post = @post
    @comment.user = current_user

    respond_to do |format|
    if @comment.save
      format.js {render :create_success}
      format.html {redirect_to post_path(@post), notice: "comment created"}
    else
      render 'posts/show'
    end
    end
  end

  def destroy
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]

    respond_to do |format|
      if can? :delete, @comment
        @comment.destroy
          format.html{redirect_to post_path(@post), notice: 'Commented deleted!'}
          format.js {render :destroy_success}
      else
        redirect_to home_path, notice: "access denied"
      end
    end


  end

private

# def authorize_user
#
#   unless can? :delete, @comment
#     redirect_to home_path, alert: "access denied"
#   end
#
# end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% user = User.find comm.user_id %>

<div class="comment" id="<%= dom_id(comm) %>">



<div class="comment-container">


  <div class="comment-header">
    <%= link_to  post_comment_path(@post, comm), method: :delete, remote: true,
    data: {confirm: 'are you sure?'}, class: 'icon-link' do%>


      <%= fa_icon "trash" %>
    <% end %>
  </div>


  <div class='comment-body'>
    <%= comm.body %>

  </div>

  <div class='comment-footer'>
    <div class='comment-author'>
        Created By: <%= user.first_name %> <br />
       On  <%=

        comm.short_create_date

         %>
    </div>
  </div>

</div>

</div>

app/views/comments/create_success.js.erb
$('#comments').append("<%= j render 'comment', comm: @comment %>");

app/views/comments/destroy_success.js.erb
$("#<%= dom_id(@comment) %>").hide()

app/views/comments/new.html.erb
<h1>Add a comment</h1>

<%= form_for @comment do |f| %>

  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>

<% end %>