config/routes.rb
Rails.application.routes.draw do


  get '/auth/google_oauth2', as: :sign_in_with_google
  get '/auth/facebook', as: :sign_in_with_facebook

  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook/callback' => 'callbacks#facebook'


  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'
  # get '/posts/new' => 'posts#new', as: :posts
  # post 'posts/new' => 'posts#create'
  #
  # get 'posts/:id' => 'posts#show', as: :post
  #
  # get 'posts/' => 'posts#index', as: :all_posts
  #
  # get 'posts/:id/edit' => 'posts#edit', as: :edit_post
  #
  # patch 'posts/:id' => 'posts#update'
  # delete 'posts/:id' => 'posts#destroy'
  #
  # get 'next_page' => 'posts#next', as: :next_page

  resources :posts do
    resources :comments
    resources :favourites, only: [:create, :destroy]
  end

  resources :users  do

    get :edit, on: :collection
    patch :update, on: :collection
    delete :destroy, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection #this bypasses having id in the url
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :current_password, :reset_token

  has_many :posts
  has_many :comments

  has_secure_password

  before_validation :downcase_email

  has_many :favourites, dependent: :destroy
  has_many :users_who_favourited_posts, through: :favourites, source: :user

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :email, presence: true,
                    uniqueness: {case_sensitive: false},
                    format: VALID_EMAIL_REGEX,
                    unless: :from_oauth?


  def full_name
  "#{first_name} #{last_name}".strip.squeeze(' ').titleize
  end

  def User.digest(string)
   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

   BCrypt::Password.create(string, cost: cost)
 end

 # Returns a random token.
 def User.new_token
   SecureRandom.urlsafe_base64
 end

 def create_reset_digest
     self.reset_token = User.new_token
     update_attribute(:reset_digest,  User.digest(reset_token))
     update_attribute(:reset_sent_at, Time.zone.now)
     puts "#{self.reset_token}"
end


def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      full_name = auth['info']['name'].split
      user.first_name = full_name[0]
      user.last_name = full_name[1]
      user.password = SecureRandom.hex(32)
      user.email = auth['info']['email']
      user.oauth_secret  = auth['credentials']['secret']
      user.oauth_raw_data =  auth
      user.provider = auth.provider
      user.uid = auth.uid
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
end

def signed_in_with_facebook?
  uid.present? && provider == 'facebook'
end


def from_oauth?
  provider.present? && uid.present?
end

  private

  def downcase_email
    self.email.downcase! if email.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)

    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path, notice: "Account Created"
    else

      render :new
    end
  end

  def edit
    @user = current_user
  end


  def update
    @user = current_user

    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)


    if @user && @user.authenticate(user_params[:current_password])

      if @user.update user_params
        redirect_to home_path, notice: "Successfully updated"
      else
        render :edit
      end
    else
      flash.now[:alert] = "Wrong credentials. Please try again."
      render :edit
    end

  end

  def destroy

    @user = current_user
    session[:user_id] = nil

    @user.destroy

    redirect_to home_path, notice: "User Successfully deleted"
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='sign-in-container'>

  <%= form_for @user do |f|  %>

  <div class='form-object'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class='form-object'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class='form-object'>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class='form-object'>
    <%= f.label :current_password %>
    <%= f.password_field :current_password %>
  </div>


  <div class='form-object'>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class='form-object'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit %>
  <%= button_to "Delete Profile", user_path(@user), method: :delete, data: {confirm: 'are you sure?'} %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class='post-grid'>

<% current_user.favourites.each do |fav| %>

<div class="post">

  <% post = fav.post %>

  <%= link_to post.title, post_path(post) %>

  <div class='post-info'>
    <span class="info-label" id="category">In  <%= post.category.title %> </span>
    <span class="info-label" id="date">on <%= post.short_create_date %></span>
    <span class="info-label" id="comment-count"><%= post.comments.count %> comments </span>

  </div>

  <div class='post-content'>
    <div class='thumbnail

    <% if post.category.title.downcase == "misc." %>
    misc
    <% else %>
    <%= post.category.title.downcase %>
    <% end %>

      '> </div>
    <p class='body-snippet'>
      <%= post.body_snippet %>
    </p>
  </div>
</div>
<% end %>

</div>

app/views/users/new.html.erb
<div class="sign-in-container">

  <%= link_to sign_in_with_google_path do %>
    <div class="btn-google"></div>
  <% end %>

  <%= link_to sign_in_with_facebook_path do %>
    <div class="btn-facebook"></div>
  <% end %>
  <div class="or-container">
      <span class="or">
        OR
      </span>
  </div>
  <br />


  <%= form_for @user do |f| %>

      <div class="form-object">
        <%= f.label :first_name %>
        <br />
        <%= f.text_field :first_name %>
      </div>
      <div class="form-object">
        <%= f.label :last_name %>
        <br />
        <%= f.text_field :last_name %>
      </div>
      <div class="form-object">
        <%= f.label :email %>
        <br />
        <%= f.email_field :email %>
      </div>
      <div class="form-object">
        <%= f.label :password %>
        <br />
        <%= f.password_field :password %>
      </div>
      <div class="form-object">
        <%= f.label :password_confirmation %>
        <br />
        <%= f.password_field :password_confirmation %>
      </div>
      <%= f.submit "Sign Up" %>

  <% end %>

</div>