config/routes.rb
Rails.application.routes.draw do


  get '/auth/google_oauth2', as: :sign_in_with_google
  get '/auth/facebook', as: :sign_in_with_facebook

  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook/callback' => 'callbacks#facebook'


  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'
  # get '/posts/new' => 'posts#new', as: :posts
  # post 'posts/new' => 'posts#create'
  #
  # get 'posts/:id' => 'posts#show', as: :post
  #
  # get 'posts/' => 'posts#index', as: :all_posts
  #
  # get 'posts/:id/edit' => 'posts#edit', as: :edit_post
  #
  # patch 'posts/:id' => 'posts#update'
  # delete 'posts/:id' => 'posts#destroy'
  #
  # get 'next_page' => 'posts#next', as: :next_page

  resources :posts do
    resources :comments
    resources :favourites, only: [:create, :destroy]
  end

  resources :users  do

    get :edit, on: :collection
    patch :update, on: :collection
    delete :destroy, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection #this bypasses having id in the url
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :post


  validates :user_id, presence: true
  validates :post_id, presence: true, uniqueness: {scope: :user_id}
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  before_action :authenticate_user

  def create
      @post = Post.find params[:post_id]
      @favourite = Favourite.new(user: current_user, post: @post)

      respond_to do |format|
        if cannot? :favourite, @post
          format.html {redirect_to :back, notice: "Access Denied" }
        elsif @favourite.save
          format.js {render :favourite_success}
          format.html {redirect_to :back, notice: "🔅Thanks for favouriting🔅" }
        else
          format.html {redirect_to :back, alert: @favourite.errors.full_messages.join(", ") }
        end
      end
  end

  def destroy
    @favourite = Favourite.find params[:id]
    @post = @favourite.post

    respond_to do |format|
      if @favourite.destroy
        format.js {render :unfavourite_success}
        format.html {redirect_to :back, notice: "🔅Unliked🔅"}
      else
        format.html {redirect_to :back, alert: @favourite.errors.full_messages.join(", ") }
      end
    end
  end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_favourite.html.erb
<div id="favourite">
  <% if user_signed_in? && can?(:favourite, @post)%>
          <% if favourite %>

            <%= link_to post_favourite_path(post, favourite), method: :delete, remote: true do %>
              <%= fa_icon "bookmark" %>
            <% end %>

          <% else %>

            <%= link_to  post_favourites_path(post), method: :post, remote: true do %>
              <%= fa_icon "bookmark-o" %>
            <% end %>

          <% end %>

  <% end %>

</div>

app/views/favourites/create.html.erb
<h1>Favourites#create</h1>
<p>Find me in app/views/favourites/create.html.erb</p>

app/views/favourites/destroy.html.erb
<h1>Favourites#destroy</h1>
<p>Find me in app/views/favourites/destroy.html.erb</p>

app/views/favourites/favourite_success.js.erb
$('#favourite').replaceWith("<%= j render('favourite', favourite: @favourite, post: @post)%>")

app/views/favourites/unfavourite_success.js.erb
$('#favourite').replaceWith("<%= j render('favourite', favourite: @favourite, post: @post)%>")