config/routes.rb
Rails.application.routes.draw do


  get '/auth/google_oauth2', as: :sign_in_with_google
  get '/auth/facebook', as: :sign_in_with_facebook

  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook/callback' => 'callbacks#facebook'


  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'
  # get '/posts/new' => 'posts#new', as: :posts
  # post 'posts/new' => 'posts#create'
  #
  # get 'posts/:id' => 'posts#show', as: :post
  #
  # get 'posts/' => 'posts#index', as: :all_posts
  #
  # get 'posts/:id/edit' => 'posts#edit', as: :edit_post
  #
  # patch 'posts/:id' => 'posts#update'
  # delete 'posts/:id' => 'posts#destroy'
  #
  # get 'next_page' => 'posts#next', as: :next_page

  resources :posts do
    resources :comments
    resources :favourites, only: [:create, :destroy]
  end

  resources :users  do

    get :edit, on: :collection
    patch :update, on: :collection
    delete :destroy, on: :collection
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection #this bypasses having id in the url
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <navbar class="navbar">

      <div class="top-bar">
        <div class="site-info">
          <h1>Programming Blog</h1>
          <!-- <p>A Ruby on Rails project by: Chris Dimoff</p> -->
        </div>
      </div>


     <div class="link-bar">
       <!-- <div class="white square"></div> -->

       <!-- <div class='text'> -->
       <div class='outer-flex'>

         <div class='inner-flex'>


        <%= link_to home_path do %>
        <div class="btn-nav"><span class='nav-text'>Home</span>  </div>
          <% end %>

         <%= link_to about_path do %>
         <div class="btn-nav"> <span class='nav-text'>About</span> </div>
           <% end %>

         <%= link_to posts_path do %>
         <div class="btn-nav"> <span class='nav-text'>All Posts</span> </div>
           <% end %>

          </div>

         <!-- <div class='pull-right'> -->
         <div class="inner-flex">



           <% if session[:user_id].present? %>


              <%= link_to  edit_users_path do %>
              <div class="btn-nav nav-large"><span class='nav-text'> Hello <%= current_user.first_name %></span> </div>
                <% end %>


              <%= link_to sessions_path, method: :delete do %>
              <div class="btn-nav"> <span class='nav-text'>Sign Out </span></div>
              <% end %>


              <%= link_to  users_path do %>
              <div class="btn-nav"> <span class='nav-text'>Favourites</span> </div>
                <% end %>


              <%= link_to new_post_path do %>
              <div class="btn-nav"><span class='nav-text'>New Post </span> </div>
                <% end %>


           <% else %>


              <%= link_to  new_user_path do %>
              <div class="btn-nav"> <span class='nav-text'>Sign Up</span> </div>
                <% end %>


              <%= link_to new_session_path do %>
              <div class="btn-nav"> <span class='nav-text'>Sign in</span></div>
                <% end %>




            <% end %>
          </div>

        </div>
        <!-- <div class="white square pull-right"></div> -->
    </div>
  </navbar>

    <div class="main">
      <%= notice || alert %>
      <%= yield %>
    </div>

  </body>


</html>